services:
  - type: web
    name: resume-analyser-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        fromSecret: gemini_api_key
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
